# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thz-Visualization' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thz-Visualization

	pod 'Alamofire', '~> 4.3'
	pod 'SwiftCharts', '~> 0.5'
   	pod 'SkyFloatingLabelTextField', '~> 2.0.0'
	pod 'AlamofireObjectMapper', '~> 4.0'
end
